# -----------------------------------------------------
#  Copyright Iliass Mahjoub 2022.                     
#  Distributed under the Boost Software License,      
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)   
# -----------------------------------------------------

name: vcxproj_generator_codecov
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run scripts and collect coverage
        run: pytest --cov scripts
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
